//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maple_Demo1.MyDemoService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyDemoService1.MyDemoServiceSoap")]
    public interface MyDemoServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetWebServiceMsgResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWebServiceMsg", ReplyAction="*")]
        Maple_Demo1.MyDemoService1.GetWebServiceMsgResponse GetWebServiceMsg(Maple_Demo1.MyDemoService1.GetWebServiceMsgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebServiceMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebServiceMsg", Namespace="http://tempuri.org/", Order=0)]
        public Maple_Demo1.MyDemoService1.GetWebServiceMsgRequestBody Body;
        
        public GetWebServiceMsgRequest() {
        }
        
        public GetWebServiceMsgRequest(Maple_Demo1.MyDemoService1.GetWebServiceMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWebServiceMsgRequestBody {
        
        public GetWebServiceMsgRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebServiceMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebServiceMsgResponse", Namespace="http://tempuri.org/", Order=0)]
        public Maple_Demo1.MyDemoService1.GetWebServiceMsgResponseBody Body;
        
        public GetWebServiceMsgResponse() {
        }
        
        public GetWebServiceMsgResponse(Maple_Demo1.MyDemoService1.GetWebServiceMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWebServiceMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWebServiceMsgResult;
        
        public GetWebServiceMsgResponseBody() {
        }
        
        public GetWebServiceMsgResponseBody(string GetWebServiceMsgResult) {
            this.GetWebServiceMsgResult = GetWebServiceMsgResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyDemoServiceSoapChannel : Maple_Demo1.MyDemoService1.MyDemoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyDemoServiceSoapClient : System.ServiceModel.ClientBase<Maple_Demo1.MyDemoService1.MyDemoServiceSoap>, Maple_Demo1.MyDemoService1.MyDemoServiceSoap {
        
        public MyDemoServiceSoapClient() {
        }
        
        public MyDemoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyDemoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyDemoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyDemoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maple_Demo1.MyDemoService1.GetWebServiceMsgResponse Maple_Demo1.MyDemoService1.MyDemoServiceSoap.GetWebServiceMsg(Maple_Demo1.MyDemoService1.GetWebServiceMsgRequest request) {
            return base.Channel.GetWebServiceMsg(request);
        }
        
        public string GetWebServiceMsg() {
            Maple_Demo1.MyDemoService1.GetWebServiceMsgRequest inValue = new Maple_Demo1.MyDemoService1.GetWebServiceMsgRequest();
            inValue.Body = new Maple_Demo1.MyDemoService1.GetWebServiceMsgRequestBody();
            Maple_Demo1.MyDemoService1.GetWebServiceMsgResponse retVal = ((Maple_Demo1.MyDemoService1.MyDemoServiceSoap)(this)).GetWebServiceMsg(inValue);
            return retVal.Body.GetWebServiceMsgResult;
        }
    }
}
