// <auto-generated />
namespace MapleMvc01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _36647 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_36647));
        
        string IMigrationMetadata.Id
        {
            get { return "201805121352253_36647"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
